# EOQ Lab — National CRDC & Ed-Tech Data Collection

**Focus areas:**
1. **Civil Rights Data Collection (CRDC)** — expand beyond 2017–18
2. **Technology in schools** — internet, devices, digital learning

**Prerequisite:** Run `collect_education_data.ipynb` first (Phase 4 CRDC setup). This notebook **adds** new federal files and logs to the same `logs/manifest.csv`.

Run cells **top to bottom**.

In [1]:
%pip install -q requests beautifulsoup4 pandas openpyxl

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: C:\Users\saihaj\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

---
## Step 0 — Project paths & imports

In [1]:
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
elif not (PROJECT_ROOT / "data").exists() and (PROJECT_ROOT.parent / "data").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from federal_collect import (
    CRDC_PUBLIC_ZIPS,
    crdc_api_dest_filename,
    discover_crdc_api_files,
    discover_edtech_files,
    download_to_path,
    edtech_dest_filename,
    ensure_federal_layout,
    inventory_crdc_zips,
    list_crdc_zip_topics,
    refresh_manifest,
)

PATHS = ensure_federal_layout(PROJECT_ROOT)
DOWNLOAD_LOG = PATHS["logs_dir"] / "download_log.jsonl"
MANIFEST_CSV = PATHS["logs_dir"] / "manifest.csv"
FEDERAL_DISCOVERED = PATHS["logs_dir"] / "federal_phase2_discovered_links.csv"

print("Project root:", PROJECT_ROOT.resolve())
print("CRDC folder:", PATHS["crdc_root"].resolve())
print("Ed-tech folder:", PATHS["edtech_root"].resolve())

Project root: C:\Users\saihaj\Documents\Data Collection - EOQ Lab
CRDC folder: C:\Users\saihaj\Documents\Data Collection - EOQ Lab\data\raw\federal\crdc
Ed-tech folder: C:\Users\saihaj\Documents\Data Collection - EOQ Lab\data\raw\federal\edtech

---
## Phase 1 — Download CRDC public-use zip bundles (national)

These zips contain **all U.S. states** — school and LEA CSV files.

| Year | Approx. size | Default |
|------|-------------|---------|
| 2015–16 | ~31 MB | Yes |
| 2017–18 | ~114 MB | Skip if you already downloaded in the first notebook |
| 2020–21 | ~78 MB | Yes (newer + more tech fields) |
| 2021–22 | ~800 MB | **Optional** (set flag below) |

In [2]:
# --- Phase 1 settings ---
SKIP_YEARS_ALREADY_PRESENT = True   # skip zip if file already on disk
DOWNLOAD_2017_18 = False            # you likely have this from the first notebook
DOWNLOAD_2021_22 = False            # very large; turn on only if you want the newest CRDC

YEARS_TO_DOWNLOAD = {"2015-16", "2020-21"}
if DOWNLOAD_2017_18:
    YEARS_TO_DOWNLOAD.add("2017-18")
if DOWNLOAD_2021_22:
    YEARS_TO_DOWNLOAD.add("2021-22")

phase1_records = []

for item in CRDC_PUBLIC_ZIPS:
    year = item["year"]
    if year not in YEARS_TO_DOWNLOAD:
        print(f"SKIP (not selected): {year}")
        continue

    dest = PATHS["crdc_root"] / year / item["filename"]
    if SKIP_YEARS_ALREADY_PRESENT and dest.exists() and dest.stat().st_size > 0:
        print(f"Already have: {dest.relative_to(PROJECT_ROOT)}")
        continue

    print(f"Downloading {year} CRDC zip... (may take several minutes)")
    record = download_to_path(
        item["url"],
        dest,
        description=f"CRDC public-use zip {year}",
        category="discipline",
        download_log=DOWNLOAD_LOG,
        project_root=PROJECT_ROOT,
        timeout_seconds=900,
    )
    record["local_path"] = str(dest.relative_to(PROJECT_ROOT))
    phase1_records.append(record)
    size_mb = record["bytes"] / 1024 / 1024
    print(f"  -> {record['status']}: {dest.name} ({size_mb:.1f} MB)")

if phase1_records:
    display(pd.DataFrame(phase1_records))
else:
    print("No new CRDC zips downloaded.")

Already have: data\raw\federal\crdc\2015-16\2015-16-crdc-data.zip
SKIP (not selected): 2017-18
Already have: data\raw\federal\crdc\2020-21\2020-21-crdc-data.zip
SKIP (not selected): 2021-22
No new CRDC zips downloaded.

---
## Phase 2 — Inventory CRDC topics (incl. technology)

Lists every CSV topic inside each CRDC zip. Topics matching **internet / computer / device / digital / distance** are flagged.

In [3]:
inventory_df = inventory_crdc_zips(PATHS["crdc_root"])
display(inventory_df)

TECH_KEYS = ("internet", "wifi", "computer", "device", "technology", "digital", "distance", "broadband")

for zip_path in sorted(PATHS["crdc_root"].rglob("*-crdc-data.zip")):
    year = zip_path.parent.name
    topics = list_crdc_zip_topics(zip_path)
    tech = [t for t in topics if any(k in t.lower() for k in TECH_KEYS)]
    print(f"\n{year}: {len(tech)} tech-related topics (of {len(topics)} total)")
    for t in tech:
        print(f"  - {t}")

,year,zip_file,topics,tech_topics,tech_topic_names,error
0,2015-16,2015-16-crdc-data.zip,4,0,,
1,2020-21,2020-21-crdc-data.zip,35,3,Computer Science; Distance Education; Internet...,

2015-16: 0 tech-related topics (of 4 total)

2020-21: 3 tech-related topics (of 35 total)
  - Computer Science
  - Distance Education
  - Internet Access and Devices

---
## Phase 3 — CRDC topic files from data.ed.gov (2015–16 & 2020–21)

The API gives **individual** CRDC spreadsheets (discipline, enrollment, etc.) — complements the zip bundles.

In [4]:
crdc_api_df = discover_crdc_api_files()
print(f"CRDC API file links found: {len(crdc_api_df)}")
crdc_api_df.to_csv(FEDERAL_DISCOVERED, index=False)
crdc_api_df.head(10)

CRDC API file links found: 189

,source,year_hint,category,dataset_title,format,url,description
0,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
1,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
2,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
3,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
4,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
5,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
6,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
7,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
8,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...
9,CRDC,2015-16,discipline,2015-16 Discipline Civil Rights Data Collection,XLSX,https://civilrightsdata.ed.gov/assets/download...,CRDC: 2015-16 Discipline Civil Rights Data Col...

In [5]:
# Download CRDC API files into data/raw/federal/{category}/
# (ArcGIS map links are excluded; failed URLs are logged and skipped — loop keeps going)
TARGET_API_YEARS = ("2015-16", "2015-2016", "2020-21", "2020-2021")

api_records = []
for _, row in crdc_api_df.iterrows():
    hint = str(row.get("year_hint", ""))
    blob = f"{hint} {row['dataset_title']} {row['url']}"
    if not any(y in blob for y in TARGET_API_YEARS):
        continue

    fname = crdc_api_dest_filename(row)
    dest_path = PATHS["federal_root"] / row["category"] / fname
    print(f"[{len(api_records)+1}] {row['dataset_title'][:70]}...")
    record = download_to_path(
        row["url"],
        dest_path,
        description=row["description"],
        category=row["category"],
        download_log=DOWNLOAD_LOG,
        project_root=PROJECT_ROOT,
    )
    if record["status"] == "failed":
        print(f"  -> FAILED: {record.get('error', 'unknown')[:100]}")
    elif record["status"] == "skipped_exists":
        print(f"  -> skipped (already had file): {fname}")
    else:
        print(f"  -> downloaded: {fname}")
    record["local_path"] = str(dest_path.relative_to(PROJECT_ROOT))
    api_records.append(record)

print(f"\nCRDC API downloads attempted: {len(api_records)}")
downloaded = sum(1 for r in api_records if r["status"] == "downloaded")
skipped = sum(1 for r in api_records if r["status"] == "skipped_exists")
failed = sum(1 for r in api_records if r["status"] == "failed")
print(f"New downloads: {downloaded}, skipped: {skipped}, failed: {failed}")

[1] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Preschool-Discipline.xlsx
[2] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Preschool-Expulsions.xlsx
[3] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Preschool-One-or-More-out-of-school-suspensions.xlsx
[4] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Preschool-More-than-one-out-of-school-suspension.xlsx
[5] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Preschool-One-out-of-school-suspension.xlsx
[6] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Preschool-Corporal-Punishment.xlsx
[7] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Days-missed-due-to-out-of-school-suspensions.xlsx
[8] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Transferred-to-alternative-school.xlsx
[9] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Referral-to-law-enforcement.xlsx
[10] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Expulsions-with-and-without-educational-services.xlsx
[11] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Expulsions-with-educational-services.xlsx
[12] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_More-than-one-out-of-school-suspension.xlsx
[13] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_In-school-suspensions.xlsx
[14] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_School-related-arrests.xlsx
[15] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Expulsions-due-to-zero-tolerance-policies.xlsx
[16] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Expulsions-without-educational-services.xlsx
[17] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_One-or-more-out-of-school-suspensions.xlsx
[18] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_One-out-of-school-suspension.xlsx
[19] 2015-16 Discipline Civil Rights Data Collection...
  -> downloaded: 2015-16_Corporal-Punishment.xlsx
[20] 2015-16 Advanced Placement Civil Rights Data Collection...
  -> downloaded: 2015-16_Advanced-Placement-Other-Subjects-Enrollment.xlsx
[21] 2015-16 Advanced Placement Civil Rights Data Collection...
  -> downloaded: 2015-16_Advanced-Placement-Science-Enrollment.xlsx
[22] 2015-16 Advanced Placement Civil Rights Data Collection...
  -> downloaded: 2015-16_Advanced-Placement-Mathematics-Enrollment.xlsx
[23] 2015-16 Advanced Placement Civil Rights Data Collection...
  -> downloaded: 2015-16_Advanced-Placement-Enrollment.xlsx
[24] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-codebook.xls
[25] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-al-aug-2018.csv
[26] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-al-oct-2018.csv
[27] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[28] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ak-oct-2018.csv
[29] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-az-aug-2018.csv
[30] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-az-oct-2018.csv
[31] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ar-aug-2018.csv
[32] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ar-oct-2018.csv
[33] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ca-aug-2018.csv
[34] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[35] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-co-aug-2018.csv
[36] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-co-oct-2018.csv
[37] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ct-aug-2018.csv
[38] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ct-oct-2018.csv
[39] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[40] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-de-oct-2018.csv
[41] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-dc-aug-2018.csv
[42] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-dc-oct-2018.csv
[43] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-fl-aug-2018.csv
[44] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-fl-oct-2018.csv
[45] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ga-aug-2018.csv
[46] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[47] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[48] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[49] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[50] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-id-oct-2018.csv
[51] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-il-aug-2018.csv
[52] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-il-oct-2018.csv
[53] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-in-aug-2018.csv
[54] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[55] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ia-aug-2018.csv
[56] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ia-oct-2018.csv
[57] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ks-aug-2018.csv
[58] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ks-oct-2018.csv
[59] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ky-aug-2018.csv
[60] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[61] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[62] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-la-oct-2018.csv
[63] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[64] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-me-oct-2018.csv
[65] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-md-aug-2018.csv
[66] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-md-oct-2018.csv
[67] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[68] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ma-oct-2018.csv
[69] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-mi-aug-2018.csv
[70] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-mi-oct-2018.csv
[71] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[72] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-mn-oct-2018.csv
[73] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ms-aug-2018.csv
[74] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ms-oct-2018.csv
[75] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-mo-aug-2018.csv
[76] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-mo-oct-2018.csv
[77] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-mt-aug-2018.csv
[78] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-mt-oct-2018.csv
[79] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ne-aug-2018.csv
[80] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ne-oct-2018.csv
[81] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-nv-aug-2018.csv
[82] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-nv-oct-2018.csv
[83] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[84] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-nh-oct-2018.csv
[85] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-nj-aug-2018.csv
[86] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-nj-oct-2018.csv
[87] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-nm-aug-2018.csv
[88] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-nm-oct-2018.csv
[89] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[90] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[91] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-nc-aug-2018.csv
[92] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-nc-oct-2018.csv
[93] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[94] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-nd-oct-2018.csv
[95] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-oh-aug-2018.csv
[96] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-oh-oct-2018.csv
[97] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[98] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ok-oct-2018.csv
[99] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-or-aug-2018.csv
[100] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-or-oct-2018.csv
[101] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-pa-aug-2018.csv
[102] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-pa-oct-2018.csv
[103] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ri-aug-2018.csv
[104] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ri-oct-2018.csv
[105] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-sc-aug-2018.csv
[106] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-sc-oct-2018.csv
[107] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-sd-aug-2018.csv
[108] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-sd-oct-2018.csv
[109] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[110] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-tn-oct-2018.csv
[111] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-tx-aug-2018.csv
[112] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[113] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-ut-aug-2018.csv
[114] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-ut-oct-2018.csv
[115] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-vt-aug-2018.csv
[116] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-vt-oct-2018.csv
[117] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-va-aug-2018.csv
[118] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-va-oct-2018.csv
[119] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 504 Server Error: Gateway Time-out for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c13
[120] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-wa-oct-2018.csv
[121] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-wv-aug-2018.csv
[122] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-wv-oct-2018.csv
[123] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-wi-aug-2018.csv
[124] Civil Rights Data Collection State Files 2015-16...
  -> FAILED: 502 Server Error: Bad Gateway for url: https://data.ed.gov/dataset/1aaf0125-13d8-4237-87d1-3c137bb89
[125] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc-2015-16-wy-aug-2018.csv
[126] Civil Rights Data Collection State Files 2015-16...
  -> downloaded: 2015-16_crdc2015-16-wy-oct-2018.csv
[127] 2015-16 Student Enrollment Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-ELL.xlsx
[128] 2015-16 Student Enrollment Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-Section-504-only.xlsx
[129] 2015-16 Student Enrollment Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-IDEA.xlsx
[130] 2015-16 Student Enrollment Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-Overall.xlsx
[131] 2015-16 Classroom Teachers Civil Rights Data Collection...
  -> downloaded: 2015-16_FTE-Support-Staff-High-School.xlsx
[132] 2015-16 Classroom Teachers Civil Rights Data Collection...
  -> downloaded: 2015-16_FTE-Support-Staff-Middle-School.xlsx
[133] 2015-16 Classroom Teachers Civil Rights Data Collection...
  -> downloaded: 2015-16_FTE-Support-Staff-Elementary-School.xlsx
[134] 2015-16 Classroom Teachers Civil Rights Data Collection...
  -> downloaded: 2015-16_Teacher-Retention.xlsx
[135] 2015-16 Classroom Teachers Civil Rights Data Collection...
  -> downloaded: 2015-16_Teacher-Certification-and-Years-of-Experience.xlsx
[136] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-12.xlsx
[137] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-11.xlsx
[138] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-10.xlsx
[139] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-9.xlsx
[140] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-8.xlsx
[141] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-7.xlsx
[142] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-6.xlsx
[143] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-5.xlsx
[144] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-4.xlsx
[145] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-3.xlsx
[146] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-2.xlsx
[147] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Grade-1.xlsx
[148] 2015-16 Student Retention Civil Rights Data Collection...
  -> downloaded: 2015-16_Retention-in-Kindergarten.xlsx
[149] 2015-16 SAT/ACT Participation Civil Rights Data Collection...
  -> downloaded: 2015-16_SAT-or-ACT-Participation-by-State.xlsx
[150] 2015-16 International Baccalaureate Enrollment Civil Rights Data Colle...
  -> downloaded: 2015-16_IB-Enrollment-by-State.xlsx
[151] 2015-16 Restraint and Seclusion Civil Rights Data Collection...
  -> downloaded: 2015-16_Offenses.xlsx
[152] 2015-16 Restraint and Seclusion Civil Rights Data Collection...
  -> downloaded: 2015-16_Seclusion.xlsx
[153] 2015-16 Restraint and Seclusion Civil Rights Data Collection...
  -> downloaded: 2015-16_Physical-Restraint.xlsx
[154] 2015-16 Restraint and Seclusion Civil Rights Data Collection...
  -> downloaded: 2015-16_Mechanical-Restraint.xlsx
[155] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Physics.xlsx
[156] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Chemistry.xlsx
[157] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Biology.xlsx
[158] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Calculus.xlsx
[159] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Advanced-Mathematics.xlsx
[160] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Algebra-II.xlsx
[161] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Geometry-in-High-School.xlsx
[162] 2015-16 Mathematics and Science Civil Rights Data Collection...
  -> downloaded: 2015-16_Enrollment-in-Geometry-in-Grade-8.xlsx
[163] 2015-16 Mathematics and Science Civil Rights Data Collection...

---
## Phase 4 — NCES / ED ed-tech survey downloads

National surveys on **technology in schools**, **internet access**, and **teacher technology use**.

In [2]:
edtech_df = discover_edtech_files()
print(f"Ed-tech file links found: {len(edtech_df)}")
edtech_df.head(10)

Ed-tech file links found: 52

,source,category,dataset_title,format,url,description
0,NCES/FRSS,other,"Educational Technology in Public Schools, 2008",ZIP,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Educational Technology in Public Scho...
1,NCES/FRSS,other,Educational Technology in Public School Distri...,ZIP,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Educational Technology in Public Scho...
2,NCES/FRSS,other,"Internet Access in U.S. Public Schools, 2003",ZIP,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Internet Access in U.S. Public School...
3,NCES/FRSS,other,Teachers' Use of Educational Technology in U.S...,ZIP,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Teachers' Use of Educational Technolo...
4,NCES/ED,other,"Educational Technology in Public Schools, 2008",ZIPPED SAS,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Educational Technology in Public Scho...
5,NCES/ED,other,Educational Technology in Public School Distri...,ZIPPED SAS,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Educational Technology in Public Scho...
6,NCES/ED,other,Teachers' Use of Educational Technology in U.S...,ZIPPED SAS,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Teachers' Use of Educational Technolo...
7,NCES/ED,other,"Internet Access in U.S. Public Schools, 2003",ZIPPED SAS,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Internet Access in U.S. Public School...
8,NCES/ED,other,Distance Education Courses for Public Elementa...,ZIPPED DAT,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Distance Education Courses for Public...
9,NCES/ED,other,Distance Education Courses for Public Elementa...,ZIPPED SAS,https://nces.ed.gov/surveys/frss/download/data...,Ed-tech: Distance Education Courses for Public...

In [3]:
edtech_records = []
for i, row in edtech_df.iterrows():
    fname = edtech_dest_filename(row)
    dest_path = PATHS["edtech_root"] / fname
    print(f"[{i+1}/{len(edtech_df)}] {row['dataset_title'][:65]}...")
    record = download_to_path(
        row["url"],
        dest_path,
        description=row["description"],
        category="other",
        download_log=DOWNLOAD_LOG,
        project_root=PROJECT_ROOT,
    )
    if record["status"] == "failed":
        print(f"  -> FAILED: {record.get('error', 'unknown')[:100]}")
    elif record["status"] == "skipped_exists":
        print(f"  -> skipped (already had file): {fname}")
    else:
        print(f"  -> downloaded: {fname}")
    record["local_path"] = str(dest_path.relative_to(PROJECT_ROOT))
    edtech_records.append(record)

print(f"\nEd-tech downloads attempted: {len(edtech_records)}")
downloaded = sum(1 for r in edtech_records if r["status"] == "downloaded")
skipped = sum(1 for r in edtech_records if r["status"] == "skipped_exists")
failed = sum(1 for r in edtech_records if r["status"] == "failed")
print(f"New downloads: {downloaded}, skipped: {skipped}, failed: {failed}")

[1/52] Educational Technology in Public Schools, 2008...
  -> downloaded: f92data.zip
[2/52] Educational Technology in Public School Districts, 2008...
  -> downloaded: f93data.zip
[3/52] Internet Access in U.S. Public Schools, 2003...
  -> downloaded: f86data.zip
[4/52] Teachers' Use of Educational Technology in U.S. Public Schools, 2...
  -> downloaded: f95data.zip
[5/52] Educational Technology in Public Schools, 2008...
  -> downloaded: f92sas.zip
[6/52] Educational Technology in Public School Districts, 2008...
  -> downloaded: f93sas.zip
[7/52] Teachers' Use of Educational Technology in U.S. Public Schools, 2...
  -> downloaded: f95sas.zip
[8/52] Internet Access in U.S. Public Schools, 2003...
  -> downloaded: f86sas.zip
[9/52] Distance Education Courses for Public Elementary and Secondary Sc...
  -> downloaded: f89data.zip
[10/52] Distance Education Courses for Public Elementary and Secondary Sc...
  -> downloaded: f89sas.zip
[11/52] Distance Education Courses for Public Elementary and Secondary Sc...
  -> downloaded: f84data.zip
[12/52] Distance Education Courses for Public Elementary and Secondary Sc...
  -> downloaded: f84sas.zip
[13/52] Distance Education Courses for Public Elementary and Secondary Sc...
  -> downloaded: f98data.zip
[14/52] Distance Education Courses for Public Elementary and Secondary Sc...
  -> downloaded: f98sas.zip
[15/52] Career and Technical Education Programs in Public School District...
  -> downloaded: 2018029_sas.zip
[16/52] Internet Access in U.S. Public Schools, 2005...
  -> downloaded: f90data.zip
[17/52] Internet Access in U.S. Public Schools, 2005...
  -> downloaded: f90sas.zip
[18/52] Foods and Physical Activity in Public Elementary Schools, 2005...
  -> downloaded: f87data.zip
[19/52] Foods and Physical Activity in Public Elementary Schools, 2005...
  -> downloaded: f87sas.zip
[20/52] National Public Education Financial Survey, 2006-07...
  -> downloaded: sas_071b.zip
[21/52] National Public Education Financial Survey, 2007-08...
  -> downloaded: SAS_081b.zip
[22/52] National Public Education Financial Survey, 2008-09...
  -> downloaded: stfis091b_sas.zip
[23/52] National Public Education Financial Survey, 2010-11...
  -> downloaded: stfis111a_sas.zip
[24/52] Service-Learning and Community Service in K-12 Public Schools, 19...
  -> downloaded: f71data.zip
[25/52] Service-Learning and Community Service in K-12 Public Schools, 19...
  -> downloaded: f71sas.zip
[26/52] Advanced Telecommunications in U.S. Private Schools, 1998-99...
  -> downloaded: f68data.zip
[27/52] Advanced Telecommunications in U.S. Private Schools, 1998-99...
  -> downloaded: f68sas.zip
[28/52] Performance -- Child Care Access Means Parents in School Program...
  -> downloaded: ccampisanalysisjuly2007.xls
[29/52] IPEDS Access Database 2018-19...
  -> FAILED: 404 Client Error: Not Found for url: https://nces.ed.gov/ipeds/tablefiles/zipfiles/IPEDS_2018-19_Pro
[30/52] IPEDS Access Database 2017-18...
  -> downloaded: IPEDS_2017-18_Final.zip
[31/52] Increasing Access to High-Quality Early Childhood Education 2013...
  -> FAILED: 404 Client Error: Not Found for url: https://www.ed.gov/sites/ed/files/about/inits/ed/earlylearning/
[32/52] Public Libraries Survey, Fiscal Year 2002...
  -> FAILED: 404 Client Error: Not Found for url: https://www.imls.gov/assets/1/AssetManager/pupld02b_csv.zip
[33/52] Public Libraries Survey, Fiscal Year 2002...
  -> FAILED: 404 Client Error: Not Found for url: https://www.imls.gov/assets/1/AssetManager/pupld02b_sas.zip
[34/52] Public School Locations 2018-19...
  -> downloaded: EDGE_GEOCODE_PUBLICSCH_1819.zip
[35/52] Public School Locations 2015-16...
  -> downloaded: EDGE_GEOCODE_PUBLICSCH_1516.zip
[36/52] Public School Locations 2016-17...
  -> downloaded: EDGE_GEOCODE_PUBLICSCH_1617.zip
[37/52] Arts Education Surveys of Secondary School Teachers, 2009...
  -> downloaded: f103data_1.zip
[38/52] Arts Education Surveys of Secondary School Teachers, 2009...
  -> FAILED: 404 Client Error: Not Found for url: https://nces.ed.gov/surveys/frss/download/data/f103data_2.zip
[39/52] Arts Education Surveys of Secondary School Teachers, 2009...
  -> downloaded: f103sas_1.zip
[40/52] Arts Education Surveys of Secondary School Teachers, 2009...
  -> downloaded: f103sas_2.zip
[41/52] Arts Education Surveys of Elementary School Teachers, 2009...
  -> downloaded: f102data.zip
[42/52] Arts Education Surveys of Elementary School Teachers, 2009...
  -> downloaded: f102sas.zip
[43/52] Teaching and Learning International Survey, 2013...
  -> downloaded: 2016063_CODEBOOKS.ZIP
[44/52] Teaching and Learning International Survey, 2013...
  -> downloaded: 2016063_SPSS.ZIP
[45/52] School Improvement 2010 Grants...
  -> downloaded: userssharedsdfschoolimprovement2010grants.csv
[46/52] After-School Programs at Public Elementary Schools, 2008...
  -> downloaded: f91data.zip
[47/52] After-School Programs at Public Elementary Schools, 2008...
  -> downloaded: f91sas.zip
[48/52] EDFacts School Improvement Grant, 2011-12...
  -> FAILED: 404 Client Error: Not Found for url: https://www.ed.gov/sites/ed/files/programs/sif/edfactssiglidata
[49/52] Consolidated State Performance Report, 2010-11...
  -> downloaded: userssharedsdflealvlachvmntrsltsforstateassmntsinrlasy201011.csv
[50/52] Consolidated State Performance Report, 2010-11...
  -> downloaded: achvmntrsltsstateassmtsrlasy201011.csv
[51/52] Consolidated State Performance Report, 2010-11...
  -> downloaded: userssharedsdfleaachvrsltsassessmathematicssy201011.csv
[52/52] Consolidated State Performance Report, 2010-11...
  -> downloaded: achvmntrsltsstateassmtsmathssy201011.csv

Ed-tech downloads attempted: 52
New downloads: 46, skipped: 0, failed: 6

---
## Phase 5 — Refresh manifest & summary

In [4]:
# Works on its own if you already ran Phases 1-4 — just run Step 0 first if kernel was restarted
if "PATHS" not in globals():
    raise NameError("Run Step 0 (imports) first, then re-run this cell.")

manifest = refresh_manifest(DOWNLOAD_LOG, MANIFEST_CSV)

fed = manifest[manifest["state"] == "federal"] if not manifest.empty else pd.DataFrame()

summary_rows = [
    {"location": "data/raw/federal/crdc/", "files": sum(1 for p in PATHS["crdc_root"].rglob("*") if p.is_file())},
    {"location": "data/raw/federal/edtech/", "files": sum(1 for p in PATHS["edtech_root"].rglob("*") if p.is_file())},
    {"location": "data/raw/federal/ (all)", "files": sum(1 for p in PATHS["federal_root"].rglob("*") if p.is_file())},
]

print("=== Collection summary ===")
print(pd.DataFrame(summary_rows).to_string(index=False))

if not fed.empty:
    print("\nFederal manifest rows by category:")
    print(fed.groupby("category").size())

print(f"\nManifest refreshed: {MANIFEST_CSV}")

=== Collection summary ===
                location  files
  data/raw/federal/crdc/      2
data/raw/federal/edtech/     46
 data/raw/federal/ (all)    347

Federal manifest rows by category:
category
discipline      79
enrollment      35
other          232
teachers        10
test_scores     32
dtype: int64

Manifest refreshed: c:\Users\saihaj\Documents\Data Collection - EOQ Lab\logs\manifest.csv